from pathlib import Path


ASKAI_PATH = Path.home() / ".askai"
API_KEY_PATH = ASKAI_PATH / "key"
CONFIG_PATH = ASKAI_PATH / "config.yml"

DEFAULT_MODEL = "text-davinci-003"
DEFAULT_NUM_ANSWERS = 1
DEFAULT_MAX_TOKENS = 300
DEFAULT_TEMPERATURE = 0.4
DEFAULT_TOP_P = 1.0
DEFAULT_FREQUENCY_PENALTY = 0.0
DEFAULT_PRESENCE_PENALTY = 0.0

MAX_INPUT_TRIES = 3
