from pathlib import Path

ASKAI_PATH = Path.home() / ".askai"
API_KEY_PATH = ASKAI_PATH / "key"
CONFIG_PATH = ASKAI_PATH / "config.yml"

DEFAULT_MODEL = "text-davinci-003"
DEFAULT_NUM_ANSWERS = 1
DEFAULT_MAX_TOKENS = 300
DEFAULT_TEMPERATURE = 0.4
DEFAULT_TOP_P = 1.0
DEFAULT_FREQUENCY_PENALTY = 0.0
DEFAULT_PRESENCE_PENALTY = 0.0

OPENAI_NUM_ANSWERS_MIN = 1
OPENAI_MAX_TOKENS_MIN = 1
OPENAI_TEMPERATURE_MIN = 0.0
OPENAI_TEMPERATURE_MAX = 2.0
OPENAI_TOP_P_MIN = 0.0
OPENAI_TOP_P_MAX = 1.0
OPENAI_FREQUENCY_PENALTY_MIN = -2.0
OPENAI_FREQUENCY_PENALTY_MAX = 2.0
OPENAI_PRESENCE_PENALTY_MIN = -2.0
OPENAI_PRESENCE_PENALTY_MAX = 2.0

MAX_INPUT_TRIES = 3
